// Real government form field templates for each form type

export const formTemplates = {
  aadhaar_update: {
    name: "Aadhaar Update Form",
    officialName: "UIDAI - Aadhaar Enrolment/Update Form",
    fields: [
      { name: "aadhaarNumber", label: "Aadhaar Number", type: "text", required: true, pattern: "\\d{12}" },
      { name: "fullName", label: "Full Name (As per Aadhaar)", type: "text", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Transgender"], required: true },
      { name: "fatherName", label: "Father's Name", type: "text", required: true },
      { name: "motherName", label: "Mother's Name", type: "text", required: false },
      { name: "address", label: "Address", type: "textarea", required: true },
      { name: "village", label: "Village/Town/City", type: "text", required: true },
      { name: "district", label: "District", type: "text", required: true },
      { name: "state", label: "State/UT", type: "text", required: true },
      { name: "postalCode", label: "Pin Code", type: "text", required: true, pattern: "\\d{6}" },
      { name: "mobileNumber", label: "Mobile Number", type: "tel", required: true, pattern: "\\d{10}" },
      { name: "email", label: "Email Address", type: "email", required: false },
    ],
  },
  pan_registration: {
    name: "PAN Application",
    officialName: "Form 49A - Application for Allotment of Permanent Account Number",
    fields: [
      {
        name: "applicationType",
        label: "Application Type",
        type: "select",
        options: ["New PAN", "Changes/Correction in PAN Data"],
        required: true,
      },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["Individual", "Company", "HUF", "Firm", "AOP", "Trust", "LLP"],
        required: true,
      },
      { name: "title", label: "Title", type: "select", options: ["Shri", "Smt", "Kumari", "M/s"], required: true },
      { name: "lastName", label: "Last Name/Surname", type: "text", required: true },
      { name: "firstName", label: "First Name", type: "text", required: true },
      { name: "middleName", label: "Middle Name", type: "text", required: false },
      { name: "nameOnCard", label: "Name to be printed on PAN Card", type: "text", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "fatherName", label: "Father's Name", type: "text", required: true },
      { name: "aadhaarNumber", label: "Aadhaar Number", type: "text", required: false, pattern: "\\d{12}" },
      { name: "flatNo", label: "Flat/Room/Door/Block No.", type: "text", required: true },
      { name: "buildingName", label: "Name of Premises/Building/Village", type: "text", required: true },
      { name: "roadStreet", label: "Road/Street/Lane/Post Office", type: "text", required: true },
      { name: "area", label: "Area/Locality/Taluka/Sub-Division", type: "text", required: true },
      { name: "city", label: "Town/City/District", type: "text", required: true },
      { name: "state", label: "State/Union Territory", type: "text", required: true },
      { name: "postalCode", label: "PIN Code", type: "text", required: true, pattern: "\\d{6}" },
      { name: "country", label: "Country", type: "text", required: true, defaultValue: "India" },
      { name: "telephone", label: "Telephone Number (with STD code)", type: "tel", required: false },
      { name: "mobileNumber", label: "Mobile Number", type: "tel", required: true, pattern: "\\d{10}" },
      { name: "email", label: "Email Address", type: "email", required: true },
    ],
  },
  passport: {
    name: "Passport Application",
    officialName: "Passport Application Form",
    fields: [
      {
        name: "applicationType",
        label: "Application Type",
        type: "select",
        options: ["Fresh Passport", "Re-issue of Passport", "Police Clearance Certificate"],
        required: true,
      },
      { name: "passportOffice", label: "Applying for Passport Office", type: "text", required: true },
      { name: "givenName", label: "Given Name (First Name + Middle Name)", type: "text", required: true },
      { name: "surname", label: "Surname", type: "text", required: true },
      {
        name: "haveChanged",
        label: "Have you ever changed your name?",
        type: "select",
        options: ["No", "Yes"],
        required: true,
      },
      { name: "dateOfBirth", label: "Date of Birth (DD/MM/YYYY)", type: "date", required: true },
      { name: "placeOfBirth", label: "Place of Birth", type: "text", required: true },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Transgender"], required: true },
      {
        name: "maritalStatus",
        label: "Marital Status",
        type: "select",
        options: ["Single", "Married", "Divorced", "Widowed", "Separated"],
        required: true,
      },
      {
        name: "citizenship",
        label: "Citizenship",
        type: "select",
        options: ["Indian"],
        required: true,
        defaultValue: "Indian",
      },
      { name: "panNumber", label: "PAN Number", type: "text", required: false },
      { name: "voterIdNumber", label: "Voter ID Number", type: "text", required: false },
      { name: "aadhaarNumber", label: "Aadhaar Number", type: "text", required: false, pattern: "\\d{12}" },
      {
        name: "employmentType",
        label: "Employment Type",
        type: "select",
        options: [
          "Government",
          "Private",
          "Self Employed",
          "Homemaker",
          "Student",
          "Retired",
          "Not Employed",
          "Others",
        ],
        required: true,
      },
      {
        name: "educationQualification",
        label: "Educational Qualification",
        type: "select",
        options: [
          "7th Pass and Below",
          "Between 8th and 9th",
          "10th Pass",
          "12th Pass",
          "Graduate",
          "Post Graduate and Above",
        ],
        required: true,
      },
      { name: "distinguishingMark", label: "Distinguishing Mark", type: "text", required: false },
      {
        name: "aadhaarEnrolmentId",
        label: "Aadhaar Enrolment ID (if Aadhaar not available)",
        type: "text",
        required: false,
      },
      { name: "fatherGivenName", label: "Father's Given Name", type: "text", required: true },
      { name: "fatherSurname", label: "Father's Surname", type: "text", required: true },
      { name: "motherGivenName", label: "Mother's Given Name", type: "text", required: true },
      { name: "motherSurname", label: "Mother's Surname", type: "text", required: true },
      { name: "legalGuardianName", label: "Legal Guardian's Name (if applicable)", type: "text", required: false },
      { name: "spouseName", label: "Spouse's Name (if married)", type: "text", required: false },
      { name: "houseNo", label: "House No. and Street Name", type: "text", required: true },
      { name: "village", label: "Village or Town or City", type: "text", required: true },
      { name: "district", label: "District", type: "text", required: true },
      { name: "state", label: "State/UT", type: "text", required: true },
      { name: "postalCode", label: "PIN Code", type: "text", required: true, pattern: "\\d{6}" },
      { name: "policeStation", label: "Police Station", type: "text", required: true },
      { name: "mobileNumber", label: "Mobile Number", type: "tel", required: true, pattern: "\\d{10}" },
      { name: "email", label: "Email Address", type: "email", required: true },
      { name: "emergencyContactName", label: "Emergency Contact Name", type: "text", required: true },
      { name: "emergencyContactPhone", label: "Emergency Contact Phone", type: "tel", required: true },
      { name: "emergencyContactAddress", label: "Emergency Contact Address", type: "textarea", required: true },
    ],
  },
  driving_license: {
    name: "Driving License Application",
    officialName: "Form 2 - Application for Learner's License / Form 4 - Application for Driving License",
    fields: [
      {
        name: "applicationType",
        label: "Application Type",
        type: "select",
        options: [
          "Fresh Learner License",
          "Fresh Driving License",
          "Renewal of Driving License",
          "Addition of New Vehicle Class",
        ],
        required: true,
      },
      { name: "fullName", label: "Full Name", type: "text", required: true },
      { name: "fatherOrHusbandName", label: "Father's/Husband's Name", type: "text", required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Transgender"], required: true },
      {
        name: "bloodGroup",
        label: "Blood Group",
        type: "select",
        options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "Unknown"],
        required: false,
      },
      { name: "qualification", label: "Educational Qualification", type: "text", required: true },
      { name: "mobileNumber", label: "Mobile Number", type: "tel", required: true, pattern: "\\d{10}" },
      { name: "email", label: "Email Address", type: "email", required: false },
      { name: "aadhaarNumber", label: "Aadhaar Number", type: "text", required: false, pattern: "\\d{12}" },
      { name: "presentAddress", label: "Present Address", type: "textarea", required: true },
      { name: "permanentAddress", label: "Permanent Address", type: "textarea", required: true },
      { name: "city", label: "City", type: "text", required: true },
      { name: "district", label: "District", type: "text", required: true },
      { name: "state", label: "State", type: "text", required: true },
      { name: "postalCode", label: "PIN Code", type: "text", required: true, pattern: "\\d{6}" },
      {
        name: "vehicleClass",
        label: "Vehicle Class Applying For",
        type: "select",
        options: [
          "MCWG (Motorcycle With Gear)",
          "MCWOG (Motorcycle Without Gear)",
          "LMV (Light Motor Vehicle)",
          "LMV-TR (Transport Vehicle)",
          "MGV (Medium Goods Vehicle)",
          "HMV (Heavy Motor Vehicle)",
        ],
        required: true,
      },
      { name: "identificationMark", label: "Identification Mark", type: "text", required: true },
      { name: "emergencyContactName", label: "Emergency Contact Name", type: "text", required: true },
      {
        name: "emergencyContactNumber",
        label: "Emergency Contact Number",
        type: "tel",
        required: true,
        pattern: "\\d{10}",
      },
    ],
  },
  visa: {
    name: "Indian Visa Application",
    officialName: "Indian Visa Application Form",
    fields: [
      {
        name: "visaType",
        label: "Visa Type",
        type: "select",
        options: [
          "Tourist Visa",
          "Business Visa",
          "Medical Visa",
          "Conference Visa",
          "Student Visa",
          "Employment Visa",
          "Transit Visa",
        ],
        required: true,
      },
      {
        name: "visaDuration",
        label: "Visa Duration",
        type: "select",
        options: ["30 Days", "1 Year", "5 Years"],
        required: true,
      },
      {
        name: "entryType",
        label: "Entry Type",
        type: "select",
        options: ["Single Entry", "Double Entry", "Multiple Entry"],
        required: true,
      },
      { name: "nationality", label: "Nationality", type: "text", required: true },
      { name: "surname", label: "Surname/Family Name", type: "text", required: true },
      { name: "givenName", label: "Given Name", type: "text", required: true },
      {
        name: "previousName",
        label: "Have you ever changed your name?",
        type: "select",
        options: ["No", "Yes"],
        required: true,
      },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Transgender"], required: true },
      { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
      { name: "placeOfBirth", label: "Place of Birth", type: "text", required: true },
      { name: "countryOfBirth", label: "Country of Birth", type: "text", required: true },
      { name: "citizenshipAcquired", label: "Citizenship/National ID No.", type: "text", required: true },
      { name: "religion", label: "Religion", type: "text", required: true },
      { name: "visibleMarks", label: "Visible identification marks", type: "text", required: true },
      {
        name: "educationQualification",
        label: "Educational Qualification",
        type: "select",
        options: [
          "Below Matriculation",
          "Matriculation",
          "Higher Secondary",
          "Graduate",
          "Post Graduate",
          "Doctorate",
          "Others",
        ],
        required: true,
      },
      { name: "presentNationality", label: "Present Nationality", type: "text", required: true },
      { name: "previousNationality", label: "Previous Nationality (if any)", type: "text", required: false },
      { name: "passportNumber", label: "Passport Number", type: "text", required: true },
      { name: "passportPlaceOfIssue", label: "Place of Issue", type: "text", required: true },
      { name: "passportDateOfIssue", label: "Date of Issue", type: "date", required: true },
      { name: "passportDateOfExpiry", label: "Date of Expiry", type: "date", required: true },
      { name: "fatherName", label: "Father's Name", type: "text", required: true },
      { name: "fatherNationality", label: "Father's Nationality", type: "text", required: true },
      { name: "fatherPlaceOfBirth", label: "Father's Place of Birth", type: "text", required: true },
      { name: "fatherCountryOfBirth", label: "Father's Country of Birth", type: "text", required: true },
      { name: "motherName", label: "Mother's Name", type: "text", required: true },
      { name: "motherNationality", label: "Mother's Nationality", type: "text", required: true },
      { name: "motherPlaceOfBirth", label: "Mother's Place of Birth", type: "text", required: true },
      { name: "motherCountryOfBirth", label: "Mother's Country of Birth", type: "text", required: true },
      {
        name: "maritalStatus",
        label: "Marital Status",
        type: "select",
        options: ["Single", "Married", "Divorced", "Widowed", "Separated"],
        required: true,
      },
      { name: "spouseName", label: "Spouse's Name (if applicable)", type: "text", required: false },
      { name: "spouseNationality", label: "Spouse's Nationality", type: "text", required: false },
      { name: "presentOccupation", label: "Present Occupation", type: "text", required: true },
      { name: "employerName", label: "Employer Name/Business", type: "text", required: true },
      { name: "employerAddress", label: "Employer Address", type: "textarea", required: true },
      { name: "homeAddress", label: "Present Address in Home Country", type: "textarea", required: true },
      { name: "homePhone", label: "Phone Number", type: "tel", required: true },
      { name: "mobileNumber", label: "Mobile Number", type: "tel", required: true },
      { name: "email", label: "Email Address", type: "email", required: true },
      { name: "addressInIndia", label: "Address in India", type: "textarea", required: true },
      { name: "contactInIndia", label: "Contact Person in India", type: "text", required: true },
      { name: "contactPhoneIndia", label: "Contact Phone in India", type: "tel", required: true },
      { name: "expectedArrivalDate", label: "Expected Date of Arrival", type: "date", required: true },
      { name: "expectedPortOfArrival", label: "Expected Port of Arrival", type: "text", required: true },
      { name: "purposeOfVisit", label: "Purpose of Visit", type: "textarea", required: true },
      { name: "placesToVisit", label: "Places to be Visited in India", type: "textarea", required: true },
      { name: "referenceInIndia1Name", label: "Reference 1 Name", type: "text", required: true },
      { name: "referenceInIndia1Phone", label: "Reference 1 Phone", type: "tel", required: true },
      { name: "referenceInIndia1Address", label: "Reference 1 Address", type: "textarea", required: true },
      {
        name: "visitedIndiaBefore",
        label: "Have you visited India before?",
        type: "select",
        options: ["No", "Yes"],
        required: true,
      },
      { name: "previousVisaNumber", label: "Previous Indian Visa Number (if any)", type: "text", required: false },
      { name: "previousVisaDate", label: "Previous Visa Date", type: "date", required: false },
    ],
  },
}

export type FormTemplateType = keyof typeof formTemplates
